version: "3.8"

services:
  app:
    image: node:18-alpine
    container_name: learn-jenkins-app
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: sh -c "npm install && npm run start"
